kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: "{{ DOMAIN }}/nfs"
            - name: NFS_SERVER
              value: "{{ nfs_ip_addresses }}"
            - name: NFS_PATH
              value: "{{ oc_nfs_path }}"
      volumes:
        - name: nfs-client-root
          nfs:
            server: "{{ nfs_ip_addresses }}"
            path: "{{ oc_nfs_path }}"
