kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: "{{ DOMAIN }}/nfs" # or choose another name, must match deployment's env PROVISIONER_NAME'
